vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        avatars:
            uri_prefix: /pictures/avatars
            upload_destination: '%kernel.project_dir%/public/pictures/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        images:
            uri_prefix: /pictures/images
            upload_destination: '%kernel.project_dir%/public/pictures/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer